{% set name = "creationism" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/creationism-{{ version }}.tar.gz
  sha256: 0d5c90f526ad1ccf16967340878c5d1b91d5f559a9996f368fed54db8268b71f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - creationism
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pypi.python.org/pypi/creationism/
  summary: Creationism is a Python library for creating objects from dictionaries.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
